name: Clean Packages

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@aegenet'
      - name: Delete old dev packages
        uses: aegenet/gh-delete-package-versions@v5.5.0
        with:
          package-name: 'ya-vite-banner'
          package-type: 'npm'
          min-versions-to-keep: 5
          include-versions: '^999\.|\-dev$'
          token: ${{ secrets.NPM_AUTH_TOKEN }}
          sleep-interval: 10000
